### ISSUE TITLE
Content filter

### ISSUE THREAD

**Issue by hspil** [W5AC-TAMU/w5ac-bot#14]
**Describe the feature you'd like**
The main reason we had the other bots was for filtering out explicit images and excessively strong language

**Comment by nayabw** [comment]
I believe Discord's in-built auto moderator can do this now. Is there anything on top of that we should add?

**Comment by hspil** [comment]
Okay, Ill have to look at what is actually doing the filtering. If we dont need anything beyond Discord builtin filtering, we can close this issue.
