### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by IanDuncanT** [W5AC-TAMU/w5ac-bot#26]
We need more comments in code to describe functionality.

**Comment by martinyis** [comment]
Hi, I would like to work on this issue, just wanna clarify to which files should we add comments.

**Comment by midikaif** [comment]
Hey @IanDuncanT, I would like to work on this issue. will you please assign this issue to me?

**Comment by IanDuncanT** [comment]
Right now, it is mostly based on describing behavior of it. I've already done the bot.js file locally, but would appreciate if y'all can start on the files in the commands directory.

**Comment by IanDuncanT** [comment]
@martinyis I've added some things in the last pull request, so make sure to pull changes before adding more. My current comments are very basic and give a baseline overview of the code.

**Comment by midikaif** [comment]
Thank you @IanDuncanT, for assigning the issue. I am working on it.
