### ISSUE TITLE
The program is not GPL compliant

### ISSUE THREAD

**Issue by nayabw** [W5AC-TAMU/w5ac-bot#36]
**Describe the bug**
I was talking to a friend and he noted that a program isn't GPL compliant unless the license is embedded.

**Expected behavior**
"Print the shortened message on startup (contains ABSOLUTELY NO WARRANTY etc.) and direct [users] to a command line switch that prints the license and quits if they want to see the whole thing" -Victor Tran (a friend)

**Additional context**
Not a major issue but we should get this added in soon if we want to continue to assert GPL compliance.

**Comment by IanDuncanT** [comment]
I don't think this is true. The link specifies that nothing is required if only running the program and not conveying it. The license defines conveying as
```To “convey” a work means any kind of propagation that enables other parties to make or receive copies. Mere interaction with a user through a computer network, with no transfer of a copy, is not conveying.```
https://www.gnu.org/licenses/gpl-faq.en.html#NoDistributionRequirements

**Comment by IanDuncanT** [comment]
Additionally, we do distribute the code here, but we include the license, so we are compliant

**Comment by nayabw** [comment]
@IanDuncanT yeah I think he and I both misinterpreted the page during our discussions. We can probably close this since we include the license in the source code.
